// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql"
)

type BotSetting struct {
	Key   string
	Value string
}

type DialogState struct {
	ChatID    int64
	State     string
	Data      sql.NullString
	UpdatedAt string
}

type Rule struct {
	ID        int64
	UserID    int64
	ChatID    int64
	Store     string
	Query     string
	City      string
	MinPrice  sql.NullString
	MaxPrice  sql.NullString
	Enabled   int64
	CreatedAt string
	UpdatedAt string
}

type User struct {
	UserID    int64
	Username  sql.NullString
	FirstName sql.NullString
	ChatID    int64
	CreatedAt string
}
