// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"
	"database/sql"
)

const createRule = `-- name: CreateRule :exec
INSERT INTO rules (user_id, chat_id, store, query, city, min_price, max_price)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateRuleParams struct {
	UserID   int64
	ChatID   int64
	Store    string
	Query    string
	City     string
	MinPrice sql.NullString
	MaxPrice sql.NullString
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) error {
	_, err := q.db.ExecContext(ctx, createRule,
		arg.UserID,
		arg.ChatID,
		arg.Store,
		arg.Query,
		arg.City,
		arg.MinPrice,
		arg.MaxPrice,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT OR IGNORE INTO users (user_id, username, first_name, chat_id)
VALUES (?, ?, ?, ?)
`

type CreateUserParams struct {
	UserID    int64
	Username  sql.NullString
	FirstName sql.NullString
	ChatID    int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.UserID,
		arg.Username,
		arg.FirstName,
		arg.ChatID,
	)
	return err
}

const deleteDialogState = `-- name: DeleteDialogState :exec
DELETE FROM dialog_state WHERE chat_id = ?
`

func (q *Queries) DeleteDialogState(ctx context.Context, chatID int64) error {
	_, err := q.db.ExecContext(ctx, deleteDialogState, chatID)
	return err
}

const deleteRule = `-- name: DeleteRule :exec
DELETE FROM rules WHERE id = ? AND user_id = ?
`

type DeleteRuleParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteRule(ctx context.Context, arg DeleteRuleParams) error {
	_, err := q.db.ExecContext(ctx, deleteRule, arg.ID, arg.UserID)
	return err
}

const getDialogState = `-- name: GetDialogState :one
SELECT chat_id, state, data, updated_at FROM dialog_state WHERE chat_id = ?
`

func (q *Queries) GetDialogState(ctx context.Context, chatID int64) (DialogState, error) {
	row := q.db.QueryRowContext(ctx, getDialogState, chatID)
	var i DialogState
	err := row.Scan(
		&i.ChatID,
		&i.State,
		&i.Data,
		&i.UpdatedAt,
	)
	return i, err
}

const getRule = `-- name: GetRule :one
SELECT id, user_id, chat_id, store, query, city, min_price, max_price, enabled, created_at, updated_at
FROM rules WHERE id = ? AND user_id = ?
`

type GetRuleParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetRule(ctx context.Context, arg GetRuleParams) (Rule, error) {
	row := q.db.QueryRowContext(ctx, getRule, arg.ID, arg.UserID)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChatID,
		&i.Store,
		&i.Query,
		&i.City,
		&i.MinPrice,
		&i.MaxPrice,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSentOffer = `-- name: GetSentOffer :one
SELECT last_price FROM sent_offers WHERE chat_id = ? AND offer_key = ?
`

type GetSentOfferParams struct {
	ChatID   int64
	OfferKey string
}

func (q *Queries) GetSentOffer(ctx context.Context, arg GetSentOfferParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getSentOffer, arg.ChatID, arg.OfferKey)
	var last_price string
	err := row.Scan(&last_price)
	return last_price, err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM bot_settings WHERE key = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const insertSentOffer = `-- name: InsertSentOffer :exec
INSERT INTO sent_offers (chat_id, offer_key, last_price)
VALUES (?, ?, ?)
`

type InsertSentOfferParams struct {
	ChatID    int64
	OfferKey  string
	LastPrice string
}

func (q *Queries) InsertSentOffer(ctx context.Context, arg InsertSentOfferParams) error {
	_, err := q.db.ExecContext(ctx, insertSentOffer, arg.ChatID, arg.OfferKey, arg.LastPrice)
	return err
}

const listEnabledRules = `-- name: ListEnabledRules :many
SELECT id, user_id, chat_id, store, query, city, min_price, max_price, enabled, created_at, updated_at
FROM rules WHERE enabled = 1 ORDER BY id
`

func (q *Queries) ListEnabledRules(ctx context.Context) ([]Rule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rule{}
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChatID,
			&i.Store,
			&i.Query,
			&i.City,
			&i.MinPrice,
			&i.MaxPrice,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRulesByUser = `-- name: ListRulesByUser :many
SELECT id, user_id, chat_id, store, query, city, min_price, max_price, enabled, created_at, updated_at
FROM rules WHERE user_id = ? ORDER BY id
`

func (q *Queries) ListRulesByUser(ctx context.Context, userID int64) ([]Rule, error) {
	rows, err := q.db.QueryContext(ctx, listRulesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rule{}
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChatID,
			&i.Store,
			&i.Query,
			&i.City,
			&i.MinPrice,
			&i.MaxPrice,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRuleEnabled = `-- name: SetRuleEnabled :exec
UPDATE rules SET enabled = ?, updated_at = datetime('now') WHERE id = ? AND user_id = ?
`

type SetRuleEnabledParams struct {
	Enabled int64
	ID      int64
	UserID  int64
}

func (q *Queries) SetRuleEnabled(ctx context.Context, arg SetRuleEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setRuleEnabled, arg.Enabled, arg.ID, arg.UserID)
	return err
}

const setSetting = `-- name: SetSetting :exec
INSERT INTO bot_settings (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) error {
	_, err := q.db.ExecContext(ctx, setSetting, arg.Key, arg.Value)
	return err
}

const updateRule = `-- name: UpdateRule :exec
UPDATE rules SET query = ?, city = ?, min_price = ?, max_price = ?, updated_at = datetime('now')
WHERE id = ? AND user_id = ?
`

type UpdateRuleParams struct {
	Query    string
	City     string
	MinPrice sql.NullString
	MaxPrice sql.NullString
	ID       int64
	UserID   int64
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) error {
	_, err := q.db.ExecContext(ctx, updateRule,
		arg.Query,
		arg.City,
		arg.MinPrice,
		arg.MaxPrice,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateSentOfferPrice = `-- name: UpdateSentOfferPrice :exec
UPDATE sent_offers SET last_price = ? WHERE chat_id = ? AND offer_key = ?
`

type UpdateSentOfferPriceParams struct {
	LastPrice string
	ChatID    int64
	OfferKey  string
}

func (q *Queries) UpdateSentOfferPrice(ctx context.Context, arg UpdateSentOfferPriceParams) error {
	_, err := q.db.ExecContext(ctx, updateSentOfferPrice, arg.LastPrice, arg.ChatID, arg.OfferKey)
	return err
}

const upsertDialogState = `-- name: UpsertDialogState :exec
INSERT INTO dialog_state (chat_id, state, data, updated_at)
VALUES (?, ?, ?, datetime('now'))
ON CONFLICT(chat_id) DO UPDATE SET state = excluded.state, data = excluded.data, updated_at = datetime('now')
`

type UpsertDialogStateParams struct {
	ChatID int64
	State  string
	Data   sql.NullString
}

func (q *Queries) UpsertDialogState(ctx context.Context, arg UpsertDialogStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertDialogState, arg.ChatID, arg.State, arg.Data)
	return err
}
